language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2.1.1
script: rspec
gemfile:
  - gemfiles/non_BIC.gemfile
  - gemfiles/BIC_rails_4.gemfile
  - gemfiles/BIC_rails_3.gemfile
